name: Python

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Устанавливаем Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip' # caching pip dependencies
      - name: Устанавливаем зависимости
        # Обновляю до последней версии pip
        # Устанавливаю pytest и зависимости из requirements.txt
        run: |
          python -m pip install --upgrade pip  
          pip install pytest
          pip install -r requirements.txt
      - name: Запускаю pytest для "test_*.py" и "*_test.py"
        run: |
          pytest .
